# Cloud Build: build l'image, la pousse dans Artifact Registry, puis déploie sur Cloud Run
substitutions:
  # ⚙️ tu peux changer la région/service ici sans toucher aux steps
  _REGION: "europe-west1"
  _LOCATION: "europe-west1"
  _SERVICE: "cv-api"
  _REPO_NAME: "cv-api"          # nom du dépôt Artifact Registry
  _IMAGE_NAME: "cv-api"         # nom de l'image

steps:
  # 1) Build
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_IMAGE_NAME}:$SHORT_SHA
      - .

  # 2) Push
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_IMAGE_NAME}:$SHORT_SHA

  # 3) Deploy Cloud Run
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE}
      - --image=${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_IMAGE_NAME}:$SHORT_SHA
      - --region=${_REGION}
      - --platform=managed
      - --allow-unauthenticated
      - --cpu=2
      - --memory=4Gi
      - --timeout=360
      # 🔐 à améliorer avec Secret Manager (voir note plus bas)
      - --set-env-vars
      - MODEL_ID=gpt-4o-mini,ALLOW_ORIGIN=https://cvout.com

images:
  - ${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_IMAGE_NAME}:$SHORT_SHA
